"""empty message

Revision ID: 849749783c6d
Revises: 1734cc2feb52
Create Date: 2016-06-11 11:29:40.638236

"""

# revision identifiers, used by Alembic.
revision = '849749783c6d'
down_revision = '1734cc2feb52'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qb_ytd_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('result_all', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qb_ytd_stats')
    ### end Alembic commands ###